### ISSUE TITLE
unable to reboot

### ISSUE THREAD

**Issue by sbarex** [uugear/Witty-Pi-4#27]
If I reboot the raspberry (from terminal with `reboot` command, or from the logout menu, reboot), the raspeberry shutdown but do not auto restart.
Without the wittypi card the reboot works.

**Comment by uugear** [comment]
It behaves like this only when serial port is not properly configured. After a quick check I believe it was due to the latest Raspberry Pi OS moved /boot/config.txt to /boot/firmware/config.txt ([detailed discussions here](https://forums.raspberrypi.com/viewtopic.php?t=364582)), and Witty Pi's software installation script still writes to the old /boot/config.txt file, which doesn't take effect anymore.

You may add "dtoverlay=miniuart-bt" to /boot/firmware/config.txt file to fix this. We will also update the software installation script to prevent such issue in the future.
